### ISSUE TITLE
Stato Termostato Attivo / Spento

### ISSUE THREAD

**Issue by SalvatoreITA** [andrea-mattioli/bticino_x8000_component#10]
### Question

Ciao andrea ho provato il tuo custom funziona bene ma si riesce ad avere lo stato del termostato se è effettivamente acceso o spento?
Nello specifico se il relè che eccita la caldaia sia in stato on o off ?

Con il vecchio addon c'era questa entità per capire se effettivamente il termostato era acceso o spento lo utilizzavo per alcune automazioni.

![aaaa](https://github.com/andrea-mattioli/bticino_x8000_component/assets/74460788/d7126fe4-1383-424c-aadf-1f67e5900e07)

Grazie per il tuo ottimo lavoro.

**Comment by andrea-mattioli** [comment]
hvac_action: heating/off/cooling

**Comment by SalvatoreITA** [comment]
Ultimo problema,non riesco a trovare un entità che mi indica le modalità in cui si trova il termostato se in modalità: Manuale o Automatica

**Comment by andrea-mattioli** [comment]
nella prossima release aggiungo 2 custom attributes:
ES.
mode: automatic
status: active
