### ISSUE TITLE
Received 401 Unauthorized error. Attempting token refresh

### ISSUE THREAD

**Issue by Vahn84** [andrea-mattioli/bticino_x8000_component#13]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

The component is not responding to any action and this error was found inside the home assistant logs

### Diagnostics information

Logger: custom_components.bticino_x8000.api
Source: custom_components/bticino_x8000/api.py:82
Integration: Bticino X8000 ([documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md), [issues](https://github.com/andrea-mattioli/bticino_x8000_component/issues))
First occurred: 08:24:19 (2 occurrences)
Last logged: 12:33:21

Received 401 Unauthorized error. Attempting token refre

### Additional information

The component was working correctly yesterday when i configured it. This issue started today

**Comment by andrea-mattioli** [comment]
I can't reproduce the problem, did you make any changes to HA or after a bad reboot?
could you give me some more info?

**Comment by Vahn84** [comment]
> I can't reproduce the problem, did you make any changes to HA or after a bad reboot? could you give me some more info?

Hey Andrea, thank you for your support. I was suddenly struggling to replicate the error and then i understood why. It was because of the firewall rules i had enabled after the integration that were blocking every connection with a geo-lock.

This is the error anyway

<img width="1007" alt="image" src="https://github.com/andrea-mattioli/bticino_x8000_component/assets/10637951/d41b664f-763f-46d7-bee5-62596afc478e">

Do you know which port/ip address i need to allow to make things work with the firewall rules enabled? Also...but this is more of a feature question...is there a way to trigger the BOOST feature of the smarther thermostat within the home assistant card?

Thank you again

Fabio

**Comment by andrea-mattioli** [comment]
https://api.developer.legrand.com
Questo è l'indirizzo che viene chiamato dall'integrazione

**Comment by Vahn84** [comment]
> https://api.developer.legrand.com Questo è l'indirizzo che viene chiamato dall'integrazione

Grazie mille Andrea, alla fine sono riuscito a sniffare l'indirizzo ip di legrand tramite wireshark su docker
