### ISSUE TITLE
Program selection

### ISSUE THREAD

**Issue by parabag** [andrea-mattioli/bticino_x8000_component#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Suggested solution

Insert a service to select the programs

### Additional information

In the previous integration this function was present

**Comment by andrea-mattioli** [comment]
WIP

**Comment by parabag** [comment]
Great, thanks!

**Comment by parabag** [comment]
Hi Andrea, any news on that? Thanks

**Comment by andrea-mattioli** [comment]
done in 0.2.0:
https://github.com/andrea-mattioli/bticino_x8000_component/releases/tag/0.2.0

**Comment by parabag** [comment]
In the services you added I cannot see the program selection...

**Comment by andrea-mattioli** [comment]
service: bticino_x8000.set_schedule

**Comment by parabag** [comment]
right, understood, I'll try, thanks

**Comment by parabag** [comment]
Working perfectly, thanks Andrea, I'll close the thread.
