### ISSUE TITLE
Boost feature

### ISSUE THREAD

**Issue by Vahn84** [andrea-mattioli/bticino_x8000_component#15]
### Question

Is there a way to trigger the boost feature of the smarther thermostat? We use that a lot, to be fair we only use that feature to heat the house. The boost was working when the thermostat was linked through the smarther thermostat app

**Comment by andrea-mattioli** [comment]
It's a service!

**Comment by Vahn84** [comment]
> It's a service!

thank you for you support andrea (if you want we can speak italian :) )

I've found the service...but it seems it doesn't let me trigger the feature

![image](https://github.com/andrea-mattioli/bticino_x8000_component/assets/10637951/0e013f7c-f146-433d-acc6-b3e1e96aa413)

**Comment by andrea-mattioli** [comment]
Devo rivedere il codice!
Forse i fix di mypy e pylint hanno introdotto qualche regressione

**Comment by Vahn84** [comment]
Ciao Andrea! ho visto l'update e il servizio sembra funzionare! Grazie! Sai dirmi se è possibile anche spegnere il boost in qualche modo?

**Comment by andrea-mattioli** [comment]
ti basta rimettere in automatico e esce dalla funzione boost
