### ISSUE TITLE
Current sensor temperature 

### ISSUE THREAD

**Issue by Toroloco84** [andrea-mattioli/bticino_x8000_component#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Suggested solution

 a sensor for the current temperature, as existing in the previous component

**Comment by andrea-mattioli** [comment]
![image](https://github.com/andrea-mattioli/bticino_x8000_component/assets/5707570/b288f5a5-c71a-4979-a969-95d278d51c5d)

**Comment by Toroloco84** [comment]
Thank you!  Today I learned something more about home assistant!  👍
