### ISSUE TITLE
Integrazione al riavvio non più disponibile

### ISSUE THREAD

**Issue by SalvatoreITA** [andrea-mattioli/bticino_x8000_component#27]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

Ciao andrea, dopo un riavvio ricevo il seguente errore e l'integrazione non viene più caricata all'avvio.

![b1](https://github.com/andrea-mattioli/bticino_x8000_component/assets/74460788/85778655-6fec-474d-ad4f-1214bb08ec0e)

**Comment by vindiesel891** [comment]
Anch’io lo stesso problema

**Comment by SalvatoreITA** [comment]
> Anch’io lo stesso problema

Stanattina ho ricaricato manualmente l'integrazione e tutto è ripartito, probabilmente un problema dei server bticino.

**Comment by andrea-mattioli** [comment]
It was a legrand server downtime, unfortunately combined with the release of the new version of HA that asks for a reboot.
At first I thought there was an incompatibility with the new release, but you can easily update.
