### ISSUE TITLE
is not a valid add-on repository

### ISSUE THREAD

**Issue by iceman7599** [andrea-mattioli/bticino_x8000_component#28]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed/try to install the latest version

### The problem

error https://github.com/andrea-mattioli/bticino_x8000_component.git is not a valid add-on repository
when adding custom repository from ADDON

### On which thermostat you have the issue?

X8000

### Which version of the Bticino X8000 component are you using?

I cannot add the component

### Which version of Home Assistant are you using?

2024.6.4

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for me?

```Text
I'm trying to add the custom repository to choose the Bticino components
```

**Comment by andrea-mattioli** [comment]
you must use hacs custom repo.
