### ISSUE TITLE
The Legrand API site is down again. - Not a BUG

### ISSUE THREAD

**Issue by andrea-mattioli** [andrea-mattioli/bticino_x8000_component#29]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

The Legrand API site is down again. I have already opened a support ticket to report the issue:
missing response from:
https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications

### Diagnostics information

none

**Comment by engal89** [comment]
Thank you for th information, same me a lot of time. The problem seems now fixed. Can you confirm?

**Comment by andrea-mattioli** [comment]
I confirm that the problem has been solved, they probably don't have anyone working on it over the weekend....
When integrations depend on the cloud like in this case, there are different stacks that come into play and it is often not easy to understand the cause of the problem.
