### ISSUE TITLE
What URL should I copy?

### ISSUE THREAD

**Issue by almico** [andrea-mattioli/bticino_x8000_component#3]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed/try to install the latest version

### The problem

I cannot go beyond the step where I should paste the browser link:
![image](https://github.com/andrea-mattioli/bticino_x8000_component/assets/15247405/bc4c4c10-bdff-4109-9f88-75df75a4b925)
In the screenshot, from the readme, the browser URL is not the same as the one copied below.
I tried some variation, but with no luck.
Is it correct to have `my.home-assistant.io` in the URL?
What should I paste?

P.S.: I don't know how to know the "Which version of the Bticino X8000 component are you using", since I am unable to configure it. Did it ever start? What string should I hunt for in the log to find the version?

### On which thermostat you have the issue?

SX8000

### Which version of the Bticino X8000 component are you using?

0.0.0

### Which version of Home Assistant are you using?

2024.1.6

### What type of installation are you running?

Home Assistant OS

**Comment by andrea-mattioli** [comment]
Follow the readme. You must provide the correct legrand's app default redirect uri as my.home-assistant.

**Comment by DjMayone** [comment]
Same for me. Link not generated after accepting the scope but redirected to the mail lovelace page.

**Comment by DjMayone** [comment]
I confirm that the link generated after accepting the scope works even if you are redirected to the main Lovelace dashboard.

**Comment by parabag** [comment]
I managed to go through the whole installation but clearly there are issues:
1. you do not have to paste the entire string, you have to replace "myassistance.io" with the response URL
2. the string to paste in the integration screen is not the one shown in the readme
3. There is a strange message error coming from the Legrand website "Error 414"

However... congratulations for the custom component!
