### ISSUE TITLE
Configuration Failed after HAOS 13 update

### ISSUE THREAD

**Issue by DjMayone** [andrea-mattioli/bticino_x8000_component#30]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

After updating HAOS to 13 version, the component stopper dorking with a "Configuration Failed" error.
Log in debug mode says: "[custom_components.bticino_x8000] Refreshing access token: None"

### Diagnostics information

[custom_components.bticino_x8000] Refreshing access token: None

**Comment by andrea-mattioli** [comment]
Legrand server ISSUE not related to integration...
![image](https://github.com/user-attachments/assets/ca8b6dbd-3296-43da-96af-019fb92a3123)
