### ISSUE TITLE
Not working and generating an error

### ISSUE THREAD

**Issue by lizardclaw8** [andrea-mattioli/bticino_x8000_component#32]
### Checks

- [X] I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)
- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

The integration is not working since today

### Diagnostics information

Registratore: homeassistant.config_entries
Fonte: config_entries.py:604
Prima occorrenza: 03:03:18 (6 occorrenze)
Ultima registrazione: 08:29:58

Error setting up entry Bticino X8000 for bticino_x8000
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 65, in async_setup_entry
    subscription_id = await add_c2c_subscription(plant_id, webhook_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 36, in add_c2c_subscription
    response = await bticino_api.set_subscribe_c2c_notifications(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/api.py", line 328, in set_subscribe_c2c_notifications
    return {"status_code": status_code, "text": json.loads(content)}
                                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by engal89** [comment]
Hi, i have same issue #31 and the problem was the service Legrand side. You have to wait some hours and retry.

I suggest to write to Legrand (as i did) to let them know there Is a problem with c2c subscription service. They didn't know about this problem. The more we write, more possibility that they try to fix. You can do It in the Legrand Api site.

**Comment by lizardclaw8** [comment]
> Hi, i have same issue #31 and the problem was the service Legrand side. You have to wait some hours and retry.
> 
> I suggest to write to Legrand (as i did) to let them know there Is a problem with c2c subscription service. They didn't know about this problem. The more we write, more possibility that they try to fix. You can do It in the Legrand Api site.

Thank you I will try it

**Comment by engal89** [comment]
You can simply ask if they confirm that there are problems with c2c subscription and It appen sometimes. They Will tell you that your callback address Is banned. Then you can wait and in the evening tell them that now Is ok, so there was some problem on Legrand side. 😊 This was my experience.

**Comment by lizardclaw8** [comment]
Working again after api call in the legrand website

closing issue

**Comment by majorhector** [comment]
> Working again after api call in the legrand website
> 
> closing issue

How can I do an api call right in the legrand website? Can you please help me?

**Comment by lizardclaw8** [comment]
> > Working again after api call in the legrand website
> > closing issue
> 
> How can I do an api call right in the legrand website? Can you please help me?

You click on the request you want and then on try it
