### ISSUE TITLE
Broken, failed after ha update

### ISSUE THREAD

**Issue by lizardclaw8** [andrea-mattioli/bticino_x8000_component#35]
### Checks

- [X] I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)
- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

Registratore: homeassistant.config_entries
Fonte: config_entries.py:604
Prima occorrenza: 20:26:07 (2 occorrenze)
Ultima registrazione: 20:30:31

Error setting up entry Bticino X8000 for bticino_x8000
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 65, in async_setup_entry
    subscription_id = await add_c2c_subscription(plant_id, webhook_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 36, in add_c2c_subscription
    response = await bticino_api.set_subscribe_c2c_notifications(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/api.py", line 328, in set_subscribe_c2c_notifications
    return {"status_code": status_code, "text": json.loads(content)}
                                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Diagnostics information

Cannot connect. C2C in legrand is working

**Comment by andrea-mattioli** [comment]
Why did you put this flag without trying it? 
"I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)"
It's a Legrand c2c ISSUE

**Comment by lizardclaw8** [comment]
> Why did you put this flag without trying it? "I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)" It's a Legrand c2c ISSUE

I have checked this and at legrand Site api test it is working 🤷🏻‍♂️

**Comment by andrea-mattioli** [comment]
![image](https://github.com/user-attachments/assets/3e2e11b1-5a10-451f-9449-45f952dc3527)

**Comment by lizardclaw8** [comment]
> ![image](https://private-user-images.githubusercontent.com/5707570/369822740-3e2e11b1-5a10-451f-9449-45f952dc3527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODUwMjksIm5iZiI6MTcyNzA4NDcyOSwicGF0aCI6Ii81NzA3NTcwLzM2OTgyMjc0MC0zZTJlMTFiMS01YTEwLTQ1MWYtOTQ0OS00NWY5NTJkYzM1MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDk0NTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdiZGZkMzc1MjZkYmY0ZDIzZTNmYzc2YjdhZGIyM2NlMmI1YmEzYmJjMjIyNmE3NzJjYTk5MzFiOTBkYTU2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WkoklsAGhEN69e9jm8cQipMMN4H6ZZGnD_b8EFGyU6w)

Thank you for your support, now it is not working for me too. Yesterday I got a normal response from testing.
