### ISSUE TITLE
Homeassistant Gitub link

### ISSUE THREAD

**Issue by DjMayone** [andrea-mattioli/bticino_x8000_component#4]
### Question

Hello Andrea,
when I fill in homeassistant custom repo with _https://github.com/andrea-mattioli/bticino_x8000_component_ it says that is not a valid add on repository.
Could you please help? Thank you!

**Comment by andrea-mattioli** [comment]
You can use hacs or copy the project inside config/custom_components

**Comment by DjMayone** [comment]
Thank you so much.
Solved adding repo in HACS.
