### ISSUE TITLE
{"message":"Internal error","code":1}

### ISSUE THREAD

**Issue by yashijoe** [andrea-mattioli/bticino_x8000_component#40]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed/try to install the latest version

### The problem

When I copy and open the proposal link before accepting the scope I got the messaggage in the browser:
{"message":"Internal error","code":1}

Thanks

### On which thermostat you have the issue?

X8000

### Which version of the Bticino X8000 component are you using?

0.2.0

### Which version of Home Assistant are you using?

2024.11.3

### What type of installation are you running?

Home Assistant OS

### Additional information

Application has been approved and I got the email with credentials
I've done the subscription to Starter Kit for Legrand APIs
I've allowed the third party access

**Comment by engal89** [comment]
I have the same problem. The integration worked well before. I had to reinstall and now i can't add the configuration to the integration. I also write a mail to Legrand, becose i think is not an integration problem but a problem of the legrand services. @yashijoe do you solve the issue in the meantime?

**Comment by fuzzybear62** [comment]
Same configuration and same response message

**Comment by engal89** [comment]
@yashijoe Legrand confirmed that was a problem of their API and fixed it. Now is working. You can retry and close the issue. I try and mine now is working.
