### ISSUE TITLE
Aggiornamento dei dati 

### ISSUE THREAD

**Issue by totofalling** [andrea-mattioli/bticino_x8000_component#46]
### Checks

- [X] I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)
- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

Ciao andrea, la tua integrazione funziona molto bene ma non aggiorna i dati in automatico. Per ovviare a questo ho fatto una autonomazione che ricarica l’integrazione ma così facendo non mi piace in quanto perde diciamo così la timeline dell’andamento del termostato.

### Diagnostics information

Xxx

**Comment by SalvatoreITA** [comment]
Occhio che dopo 500 chiamate al giorno l'api va offline

**Comment by totofalling** [comment]
> Occhio che dopo 500 chiamate al giorno l'api va offline

Lo so ma non ne fa nemmeno uno se non metto il restart dell’addon

**Comment by MassiPi** [comment]
ma è collegato ai problemi C2C di legrand?
anche io ho appena installato l'integrazione per mio fratello che ha un po' di X8000 vecchi e in effetti dice che non aggiorna i valori
grazie

**Comment by totofalling** [comment]
> ma è collegato ai problemi C2C di legrand? anche io ho appena installato l'integrazione per mio fratello che ha un po' di X8000 vecchi e in effetti dice che non aggiorna i valori grazie

No no. Se ricarichi l addon si aggiornano fino a 500 chiamate

**Comment by MassiPi** [comment]
> Se ricarichi l addon si aggiornano fino a 500 chiamate

beh converrai soluzione non pulitissima :)
eviterei di guardare nel codice, vedo un paio di pull request magari c'è qualche correzione..

**Comment by andrea-mattioli** [comment]
I dati devono arrivare da Legrand se non si aggiorna è perché non li mandano.
Il servizio C2c è un mese che non sta funzionando a dovere.
